version: '3.8'
  
services:
  escalaconnect:
    container_name: escalaconnect
    hostname: escalaconnect
    restart: always
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8090:8000"