# Generated by Django 5.1.5 on 2025-01-31 19:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escala', '0003_alter_funcao_options_alter_escala_confirmada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planejamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanejamentoFuncao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escala.funcao')),
                ('planejamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcoes', to='planejamento.planejamento')),
            ],
        ),
    ]
