"""
Django settings for escalaconnect project.

Generated by 'django-admin startproject' using Django 4.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from decouple import config, Csv
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Definido obrigatoriamente via variável de ambiente / .env (ver .env.example).
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# Domínios autorizados, separados por vírgula (ex.: "connect.simoesti.com.br,localhost")
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

DEFAULT_DOMAIN = "https://connect.simoesti.com.br"

ADMIN_PROTECTED_PATHS = [
    '/admin/',              # Exemplo de URL padrão do Django Admin
    # '/api/equip/*',           # Bloqueia todas as sub-rotas de usuario/
    '/usuario/*',           # Bloqueia todas as sub-rotas de usuario/
]

ADMIN_ALLOWED_PATHS = [
    '/usuario/perfil/',  # Libera o acesso a /usuario/perfil/
    '/api/user/signup/'
]

# Origens confiáveis para CSRF (necessário atrás de proxy HTTPS).
# Fixo no código para não depender de variável de ambiente compartilhada do servidor.
CSRF_TRUSTED_ORIGINS = [
    'https://connect.simoesti.com.br',
    'https://www.connect.simoesti.com.br',
    'https://connect.pibvp.org.br',
    'https://www.connect.pibvp.org.br',
]

# Segurança HTTPS/cookies — ativada quando DEBUG=False.
# Confia no cabeçalho do proxy reverso para reconhecer requisições HTTPS.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # Opt-in (default desligado): só ative SSL_REDIRECT após confirmar que o proxy
    # encaminha X-Forwarded-Proto, senão pode causar loop de redirecionamento.
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
    # Opt-in: HSTS é difícil de reverter (o navegador força HTTPS pelo período).
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=0, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False, cast=bool)
    SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=False, cast=bool)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'usuario',
    'equipe',
    'evento',
    'escala',
    'planejamento',
    'ocupado',
    'disponivel',


]

AUTHENTICATION_BACKENDS = [
    'usuario.backends.CustomBackend',
    'django.contrib.auth.backends.ModelBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'escalaconnect.middleware.admin_required_middleware.AdminRequiredMiddleware',
    'usuario.middleware.FirstLoginMiddleware',
    'usuario.middleware.TermoVoluntarioMiddleware',

]

ROOT_URLCONF = 'escalaconnect.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'escalaconnect.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASE_ENGINE = config('DATABASE_ENGINE', default='postgres')

if DATABASE_ENGINE == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / config('SQLITE_NAME', default='db.sqlite3'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('POSTGRES_DB', default='escalaconnect'),
            'USER': config('POSTGRES_USER', default='postgres'),
            'PASSWORD': config('POSTGRES_PASSWORD', default='postgres'),
            'HOST': config('POSTGRES_HOST', default='localhost'),
            'PORT': config('POSTGRES_PORT', default='5432'),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True  # Habilita a localização
USE_TZ = True

AUTH_USER_MODEL = 'usuario.Usuario'


# URL para servir arquivos estáticos
STATIC_URL = '/static/'

# Caminho para a pasta onde os arquivos estáticos serão armazenados (em produção)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Diretórios adicionais para buscar arquivos estáticos durante o desenvolvimento
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# WhiteNoise: comprime e serve os estáticos pela própria aplicação (gunicorn).
# Requer `python manage.py collectstatic` no deploy.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}


# LOGIN_REDIRECT_URL = '/'
# LOGIN_URL = '/login/'  # URL de login para usuários não autenticados
LOGIN_URL = '/'  # URL de login para usuários não autenticados

# HANDLER403 = '.views.custom_403'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_AGE = 1800  # 30 minutos em segundos


EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = config('EMAIL_HOST_USER2', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD2', default='')
# Remetente padrão (o "De:" dos e-mails) = o próprio noreply autenticado.
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER

# === Celery ===
# Broker
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")

# Backend de resultados
# Se USE_DJANGO_CELERY_RESULTS=true no ambiente, usa django-db (requer migrate)
USE_DJANGO_CELERY_RESULTS = os.getenv("USE_DJANGO_CELERY_RESULTS", "false").lower() == "true"

if USE_DJANGO_CELERY_RESULTS:
    CELERY_RESULT_BACKEND = "django-db"
    CELERY_RESULT_EXTENDED = True
    if "django_celery_results" not in INSTALLED_APPS:
        INSTALLED_APPS.append("django_celery_results")
else:
    CELERY_RESULT_BACKEND = os.getenv(
        "CELERY_RESULT_BACKEND",
        "redis://localhost:6379/1"
    )

# QoL
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = int(os.getenv("CELERY_TASK_TIME_LIMIT", str(60 * 5)))
CELERY_TIMEZONE = "America/Sao_Paulo"

# Execução síncrona (apenas dev)
CELERY_TASK_ALWAYS_EAGER = os.getenv("CELERY_TASK_ALWAYS_EAGER", "false").lower() == "true"
CELERY_TASK_EAGER_PROPAGATES = os.getenv("CELERY_TASK_EAGER_PROPAGATES", "true").lower() == "true"


# === Logging ===
# Saída no console (capturada pelo Docker/journald). Nível configurável por env.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": config("LOG_LEVEL", default="INFO"),
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": config("DJANGO_LOG_LEVEL", default="INFO"),
            "propagate": False,
        },
    },
}
