# Generated by Django 4.2.30 on 2026-10-02 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expo_token', models.CharField(max_length=255, unique=True)),
                ('plataforma', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10)),
                ('nome_aparelho', models.CharField(blank=True, max_length=100)),
                ('app_versao', models.CharField(blank=True, max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ultimo_uso', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['usuario', 'ativo'], name='api_device_usuario_adb0b3_idx')],
            },
        ),
    ]
