# Generated by Django 5.1.5 on 2025-09-22 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disponivel', '0001_initial'),
        ('evento', '0003_alter_evento_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponivel',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evento.evento'),
        ),
    ]
