# Generated by Django 4.2.30 on 2026-06-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disponivel', '0002_disponivel_evento'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='disponivel',
            index=models.Index(fields=['usuario', 'data_inicio', 'data_fim'], name='disponivel__usuario_bacf48_idx'),
        ),
    ]
