# Generated by Django 4.2.30 on 2026-07-09 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0006_evento_equipe'),
        ('disponivel', '0003_disponivel_disponivel__usuario_bacf48_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponivel',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evento.evento'),
        ),
    ]
