# Generated by Django 5.1.5 on 2025-01-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprovada', models.BooleanField()),
                ('data_solicitacao', models.DateTimeField()),
                ('data_aprovacao', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmada', models.BooleanField()),
                ('data_confirmacao', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprovada', models.BooleanField()),
                ('data_candidatura', models.DateTimeField()),
                ('data_aprovacao', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoTroca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitacao', models.CharField(max_length=255)),
                ('aprovada', models.BooleanField()),
                ('data_solicitacao', models.DateTimeField()),
                ('data_aprovacao', models.DateTimeField()),
            ],
        ),
    ]
