# Generated by Django 5.1.5 on 2025-01-28 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipe', '0002_initial'),
        ('escala', '0001_initial'),
        ('evento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='desistencia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escala',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.evento'),
        ),
        migrations.AddField(
            model_name='escala',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='desistencia',
            name='escala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escala.escala'),
        ),
        migrations.AddField(
            model_name='funcao',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipe.equipe'),
        ),
        migrations.AddField(
            model_name='escala',
            name='funcao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escala.funcao'),
        ),
        migrations.AddField(
            model_name='rendimento',
            name='candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rendimento',
            name='escala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escala.escala'),
        ),
        migrations.AddField(
            model_name='solicitacaotroca',
            name='escala_destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_destino', to='escala.escala'),
        ),
        migrations.AddField(
            model_name='solicitacaotroca',
            name='escala_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_origem', to='escala.escala'),
        ),
        migrations.AddField(
            model_name='solicitacaotroca',
            name='lider_aprovador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_aprovadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacaotroca',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_feitas', to=settings.AUTH_USER_MODEL),
        ),
    ]
