# Generated by Django 5.1.5 on 2025-01-31 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcao',
            options={'verbose_name': 'Função', 'verbose_name_plural': 'Funções'},
        ),
        migrations.AlterField(
            model_name='escala',
            name='confirmada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='escala',
            name='data_confirmacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
