# Generated by Django 5.1.5 on 2025-02-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0003_alter_funcao_options_alter_escala_confirmada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desistencia',
            name='motivo',
            field=models.TextField(default='motivo', verbose_name='Motivo da Desistência'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='desistencia',
            name='aprovada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='desistencia',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='desistencia',
            name='data_solicitacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
