# Generated by Django 5.1.5 on 2025-03-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0004_desistencia_motivo_alter_desistencia_aprovada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaotroca',
            name='aprovada',
            field=models.BooleanField(default=False),
        ),
    ]
