# Generated by Django 5.1.5 on 2025-03-15 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0006_alter_solicitacaotroca_data_aprovacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaotroca',
            name='lider_aprovador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_aprovadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
