# Generated by Django 5.1.5 on 2025-01-31 02:24

import usuario.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(help_text='Digite apenas os números do CPF (sem pontos ou traços).', max_length=11, unique=True, validators=[usuario.utils.validate_cpf]),
        ),
    ]
