# Generated by Django 5.1.5 on 2025-02-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
