# Generated by Django 5.1.5 on 2025-02-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_is_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='batismo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
