# Generated by Django 4.2.30 on 2026-06-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_passwordresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='termo_aceito_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='aniversario',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='batismo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
