# Generated by Django 4.2.30 on 2026-07-07 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_normaliza_telefones'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ultima_atividade',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RegistroLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_login', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['data_hora'], name='usuario_reg_data_ho_91d5fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='AtividadeDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_diarias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['data'], name='usuario_ati_data_d548be_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='atividadediaria',
            constraint=models.UniqueConstraint(fields=('usuario', 'data'), name='atividade_unica_usuario_data'),
        ),
    ]
