# Generated by Django 5.1.5 on 2025-01-31 02:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lideranca',
            unique_together={('equipe', 'usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='membrosequipe',
            unique_together={('equipe', 'usuario')},
        ),
    ]
