# Generated by Django 5.1.5 on 2025-02-02 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0003_alter_lideranca_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membrosequipe',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='equipe.equipe'),
        ),
    ]
