# Generated by Django 5.1.5 on 2025-02-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0004_alter_membrosequipe_equipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='membrosequipe',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
