# Generated by Django 4.2.30 on 2026-06-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0005_membrosequipe_aprovado'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='membrosequipe',
            index=models.Index(fields=['equipe', 'aprovado'], name='equipe_memb_equipe__ea3e0d_idx'),
        ),
    ]
