# Generated by Django 5.1.5 on 2025-02-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocupado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocupado',
            name='motivo',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
