# Generated by Django 5.1.5 on 2025-03-02 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_initial'),
        ('ocupado', '0002_ocupado_motivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocupado',
            name='motivo',
        ),
        migrations.AddField(
            model_name='ocupado',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evento.evento'),
        ),
    ]
