# Generated by Django 4.2.30 on 2026-06-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocupado', '0003_remove_ocupado_motivo_ocupado_evento'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ocupado',
            index=models.Index(fields=['usuario', 'data_inicio', 'data_fim'], name='ocupado_ocu_usuario_377a98_idx'),
        ),
    ]
