# Generated by Django 5.1.5 on 2025-03-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
