# Generated by Django 5.1.5 on 2025-10-09 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0007_alter_solicitacaotroca_lider_aprovador'),
        ('evento', '0004_notification_notificationattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='escala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='escala.escala'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='purpose',
            field=models.CharField(choices=[('confirmacao_escala', 'Confirmação de Escala'), ('availability_reminder', 'Lembrar disponibilidades'), ('lembrete_escala', 'Lembrete de Escala')], default='confirmacao_escala', max_length=40),
        ),
    ]
