# Generated by Django 4.2.30 on 2026-07-02 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0006_membrosequipe_equipe_memb_equipe__ea3e0d_idx'),
        ('evento', '0005_alter_notification_escala_alter_notification_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='equipe',
            field=models.ForeignKey(blank=True, help_text='Deixe em branco para um evento público. Se selecionar uma equipe, o evento fica visível apenas para os integrantes dela.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='equipe.equipe'),
        ),
    ]
