# Generated by Django 4.2.30 on 2026-10-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0006_evento_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('push', 'Push (app)')], default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='purpose',
            field=models.CharField(choices=[('confirmacao_escala', 'Confirmação de Escala'), ('availability_reminder', 'Lembrar disponibilidades'), ('lembrete_escala', 'Lembrete de Escala'), ('escalado', 'Escalado'), ('troca_aprovada', 'Troca aprovada'), ('desistencia_aprovada', 'Desistência aprovada'), ('membro_aprovado', 'Entrada na equipe aprovada')], default='confirmacao_escala', max_length=40),
        ),
    ]
