# Generated by Django 4.2.30 on 2026-10-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0007_alter_notification_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='purpose',
            field=models.CharField(choices=[('confirmacao_escala', 'Confirmação de Escala'), ('availability_reminder', 'Lembrar disponibilidades'), ('lembrete_escala', 'Lembrete de Escala'), ('escalado', 'Escalado'), ('troca_aprovada', 'Troca aprovada'), ('desistencia_aprovada', 'Desistência aprovada'), ('membro_aprovado', 'Entrada na equipe aprovada'), ('evento_proximo', 'Evento começa em breve')], default='confirmacao_escala', max_length=40),
        ),
    ]
